/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_POUND = 2,
  aux_sym_comment_token1 = 3,
  aux_sym_docstring_token1 = 4,
  aux_sym_docstring_token2 = 5,
  sym_whitespace = 6,
  anon_sym_import = 7,
  anon_sym_from = 8,
  sym_decimal_number = 9,
  sym_hex_number = 10,
  sym_binary_number = 11,
  sym_octal_number = 12,
  sym_float_number = 13,
  anon_sym_def = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_DASH_GT = 17,
  anon_sym_COLON = 18,
  anon_sym_COMMA = 19,
  anon_sym_EQ = 20,
  anon_sym_LBRACK = 21,
  anon_sym_RBRACK = 22,
  anon_sym_HashMap = 23,
  aux_sym_string_token1 = 24,
  aux_sym_string_token2 = 25,
  anon_sym_constant = 26,
  sym_source_file = 27,
  sym_comment = 28,
  sym_docstring = 29,
  sym_import_statement = 30,
  sym_number = 31,
  sym_function_definition = 32,
  sym_parameter_list = 33,
  sym_parameter = 34,
  sym_type = 35,
  sym_array_type = 36,
  sym_map_type = 37,
  sym_expression = 38,
  sym_call_expression = 39,
  sym_argument_list = 40,
  sym_string = 41,
  sym_constant_definition = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_parameter_list_repeat1 = 44,
  aux_sym_argument_list_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_docstring_token1] = "docstring_token1",
  [aux_sym_docstring_token2] = "docstring_token2",
  [sym_whitespace] = "whitespace",
  [anon_sym_import] = "import",
  [anon_sym_from] = "from",
  [sym_decimal_number] = "decimal_number",
  [sym_hex_number] = "hex_number",
  [sym_binary_number] = "binary_number",
  [sym_octal_number] = "octal_number",
  [sym_float_number] = "float_number",
  [anon_sym_def] = "def",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_HashMap] = "HashMap",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_constant] = "constant",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_docstring] = "docstring",
  [sym_import_statement] = "import_statement",
  [sym_number] = "number",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter] = "parameter",
  [sym_type] = "type",
  [sym_array_type] = "array_type",
  [sym_map_type] = "map_type",
  [sym_expression] = "expression",
  [sym_call_expression] = "call_expression",
  [sym_argument_list] = "argument_list",
  [sym_string] = "string",
  [sym_constant_definition] = "constant_definition",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_docstring_token1] = aux_sym_docstring_token1,
  [aux_sym_docstring_token2] = aux_sym_docstring_token2,
  [sym_whitespace] = sym_whitespace,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_from] = anon_sym_from,
  [sym_decimal_number] = sym_decimal_number,
  [sym_hex_number] = sym_hex_number,
  [sym_binary_number] = sym_binary_number,
  [sym_octal_number] = sym_octal_number,
  [sym_float_number] = sym_float_number,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_HashMap] = anon_sym_HashMap,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_constant] = anon_sym_constant,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_docstring] = sym_docstring,
  [sym_import_statement] = sym_import_statement,
  [sym_number] = sym_number,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter] = sym_parameter,
  [sym_type] = sym_type,
  [sym_array_type] = sym_array_type,
  [sym_map_type] = sym_map_type,
  [sym_expression] = sym_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_argument_list] = sym_argument_list,
  [sym_string] = sym_string,
  [sym_constant_definition] = sym_constant_definition,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_docstring_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_docstring_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [sym_decimal_number] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_number] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_number] = {
    .visible = true,
    .named = true,
  },
  [sym_octal_number] = {
    .visible = true,
    .named = true,
  },
  [sym_float_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HashMap] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_constant] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_docstring] = {
    .visible = true,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_map_type] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_constant_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 10,
  [37] = 37,
  [38] = 23,
  [39] = 39,
  [40] = 24,
  [41] = 41,
  [42] = 42,
  [43] = 25,
  [44] = 44,
  [45] = 45,
  [46] = 21,
  [47] = 20,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 65,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(44);
      ADVANCE_MAP(
        '"', 2,
        '#', 52,
        '\'', 8,
        '(', 68,
        ')', 69,
        ',', 72,
        '-', 15,
        '.', 41,
        '0', 60,
        ':', 71,
        '=', 73,
        'H', 18,
        '[', 74,
        ']', 75,
        'c', 28,
        'd', 21,
        'f', 33,
        'i', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(8);
      if (lookahead == ')') ADVANCE(69);
      if (lookahead == '.') ADVANCE(41);
      if (lookahead == '0') ADVANCE(60);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(78);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(79);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == '\'') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == '\'') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == '\'') ADVANCE(12);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '.') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(70);
      END_STATE();
    case 16:
      if (lookahead == 'H') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 17:
      if (lookahead == 'M') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(35);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(67);
      END_STATE();
    case 23:
      if (lookahead == 'h') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'm') ADVANCE(59);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(76);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 36:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 40:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 43:
      if (eof) ADVANCE(44);
      ADVANCE_MAP(
        '"', 5,
        '#', 52,
        '\'', 11,
        '(', 68,
        'c', 28,
        'd', 21,
        'f', 33,
        'i', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_docstring_token1);
      if (lookahead == '"') ADVANCE(55);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_docstring_token2);
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_whitespace);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_decimal_number);
      if (lookahead == '.') ADVANCE(65);
      if (lookahead == 'b') ADVANCE(63);
      if (lookahead == 'o') ADVANCE(64);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_decimal_number);
      if (lookahead == '.') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_hex_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_binary_number);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_octal_number);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_float_number);
      if (lookahead == 'e') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_float_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_HashMap);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_HashMap);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_constant);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 43},
  [2] = {.lex_state = 43},
  [3] = {.lex_state = 43},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 43},
  [11] = {.lex_state = 43},
  [12] = {.lex_state = 43},
  [13] = {.lex_state = 43},
  [14] = {.lex_state = 43},
  [15] = {.lex_state = 43},
  [16] = {.lex_state = 43},
  [17] = {.lex_state = 43},
  [18] = {.lex_state = 43},
  [19] = {.lex_state = 43},
  [20] = {.lex_state = 43},
  [21] = {.lex_state = 43},
  [22] = {.lex_state = 43},
  [23] = {.lex_state = 43},
  [24] = {.lex_state = 43},
  [25] = {.lex_state = 43},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 16},
  [30] = {.lex_state = 16},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 16},
  [33] = {.lex_state = 16},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 53},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [sym_decimal_number] = ACTIONS(1),
    [sym_hex_number] = ACTIONS(1),
    [sym_binary_number] = ACTIONS(1),
    [sym_octal_number] = ACTIONS(1),
    [sym_float_number] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_HashMap] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [anon_sym_constant] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(71),
    [sym_comment] = STATE(3),
    [sym_docstring] = STATE(15),
    [sym_import_statement] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_constant_definition] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [aux_sym_docstring_token1] = ACTIONS(7),
    [aux_sym_docstring_token2] = ACTIONS(7),
    [sym_whitespace] = ACTIONS(9),
    [anon_sym_import] = ACTIONS(11),
    [anon_sym_from] = ACTIONS(13),
    [anon_sym_def] = ACTIONS(15),
    [anon_sym_constant] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_POUND,
    ACTIONS(27), 1,
      sym_whitespace,
    ACTIONS(30), 1,
      anon_sym_import,
    ACTIONS(33), 1,
      anon_sym_from,
    ACTIONS(36), 1,
      anon_sym_def,
    ACTIONS(39), 1,
      anon_sym_constant,
    STATE(15), 1,
      sym_docstring,
    ACTIONS(24), 2,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
    STATE(2), 5,
      sym_comment,
      sym_import_statement,
      sym_function_definition,
      sym_constant_definition,
      aux_sym_source_file_repeat1,
  [36] = 10,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      anon_sym_import,
    ACTIONS(13), 1,
      anon_sym_from,
    ACTIONS(15), 1,
      anon_sym_def,
    ACTIONS(17), 1,
      anon_sym_constant,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 1,
      sym_whitespace,
    STATE(15), 1,
      sym_docstring,
    ACTIONS(7), 2,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
    STATE(2), 5,
      sym_comment,
      sym_import_statement,
      sym_function_definition,
      sym_constant_definition,
      aux_sym_source_file_repeat1,
  [72] = 8,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(48), 1,
      sym_decimal_number,
    ACTIONS(52), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      sym_expression,
    STATE(76), 1,
      sym_argument_list,
    ACTIONS(54), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(40), 3,
      sym_number,
      sym_call_expression,
      sym_string,
    ACTIONS(50), 4,
      sym_hex_number,
      sym_binary_number,
      sym_octal_number,
      sym_float_number,
  [103] = 8,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(48), 1,
      sym_decimal_number,
    ACTIONS(56), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      sym_expression,
    STATE(65), 1,
      sym_argument_list,
    ACTIONS(54), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(40), 3,
      sym_number,
      sym_call_expression,
      sym_string,
    ACTIONS(50), 4,
      sym_hex_number,
      sym_binary_number,
      sym_octal_number,
      sym_float_number,
  [134] = 6,
    ACTIONS(58), 1,
      sym_identifier,
    ACTIONS(60), 1,
      sym_decimal_number,
    STATE(19), 1,
      sym_expression,
    ACTIONS(64), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(24), 3,
      sym_number,
      sym_call_expression,
      sym_string,
    ACTIONS(62), 4,
      sym_hex_number,
      sym_binary_number,
      sym_octal_number,
      sym_float_number,
  [159] = 6,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(48), 1,
      sym_decimal_number,
    STATE(50), 1,
      sym_expression,
    ACTIONS(54), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(40), 3,
      sym_number,
      sym_call_expression,
      sym_string,
    ACTIONS(50), 4,
      sym_hex_number,
      sym_binary_number,
      sym_octal_number,
      sym_float_number,
  [184] = 6,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(48), 1,
      sym_decimal_number,
    STATE(69), 1,
      sym_expression,
    ACTIONS(54), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(40), 3,
      sym_number,
      sym_call_expression,
      sym_string,
    ACTIONS(50), 4,
      sym_hex_number,
      sym_binary_number,
      sym_octal_number,
      sym_float_number,
  [209] = 6,
    ACTIONS(46), 1,
      sym_identifier,
    ACTIONS(48), 1,
      sym_decimal_number,
    STATE(49), 1,
      sym_expression,
    ACTIONS(54), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    STATE(40), 3,
      sym_number,
      sym_call_expression,
      sym_string,
    ACTIONS(50), 4,
      sym_hex_number,
      sym_binary_number,
      sym_octal_number,
      sym_float_number,
  [234] = 3,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(68), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [251] = 2,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(74), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [265] = 2,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(78), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [279] = 2,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(82), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [293] = 2,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(86), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [307] = 2,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(90), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [321] = 2,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(94), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [335] = 2,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(98), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [349] = 2,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(102), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [363] = 2,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(106), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [377] = 2,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(110), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [391] = 2,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(114), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [405] = 2,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(118), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [419] = 2,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(122), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [433] = 2,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(68), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [447] = 2,
    ACTIONS(124), 2,
      ts_builtin_sym_end,
      sym_whitespace,
    ACTIONS(126), 7,
      anon_sym_POUND,
      aux_sym_docstring_token1,
      aux_sym_docstring_token2,
      anon_sym_import,
      anon_sym_from,
      anon_sym_def,
      anon_sym_constant,
  [461] = 1,
    ACTIONS(128), 6,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [470] = 1,
    ACTIONS(130), 6,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [479] = 1,
    ACTIONS(132), 6,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [488] = 4,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_HashMap,
    STATE(35), 1,
      sym_type,
    STATE(27), 2,
      sym_array_type,
      sym_map_type,
  [502] = 4,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_HashMap,
    STATE(52), 1,
      sym_type,
    STATE(27), 2,
      sym_array_type,
      sym_map_type,
  [516] = 4,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_HashMap,
    STATE(54), 1,
      sym_type,
    STATE(27), 2,
      sym_array_type,
      sym_map_type,
  [530] = 4,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_HashMap,
    STATE(53), 1,
      sym_type,
    STATE(27), 2,
      sym_array_type,
      sym_map_type,
  [544] = 4,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_HashMap,
    STATE(57), 1,
      sym_type,
    STATE(27), 2,
      sym_array_type,
      sym_map_type,
  [558] = 4,
    ACTIONS(134), 1,
      sym_identifier,
    ACTIONS(136), 1,
      anon_sym_HashMap,
    STATE(55), 1,
      sym_type,
    STATE(27), 2,
      sym_array_type,
      sym_map_type,
  [572] = 3,
    ACTIONS(140), 1,
      anon_sym_EQ,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(138), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [583] = 2,
    ACTIONS(144), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [592] = 4,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      sym_parameter,
    STATE(60), 1,
      sym_parameter_list,
  [605] = 1,
    ACTIONS(120), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [611] = 3,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(41), 1,
      aux_sym_parameter_list_repeat1,
  [621] = 1,
    ACTIONS(66), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [627] = 3,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    STATE(41), 1,
      aux_sym_parameter_list_repeat1,
  [637] = 3,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_parameter_list_repeat1,
  [647] = 1,
    ACTIONS(124), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [653] = 3,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_argument_list_repeat1,
  [663] = 3,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_argument_list_repeat1,
  [673] = 1,
    ACTIONS(112), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [679] = 1,
    ACTIONS(108), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [685] = 3,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_argument_list_repeat1,
  [695] = 1,
    ACTIONS(167), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [700] = 1,
    ACTIONS(172), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [705] = 2,
    ACTIONS(174), 1,
      anon_sym_DASH_GT,
    ACTIONS(176), 1,
      anon_sym_COLON,
  [712] = 2,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(178), 1,
      anon_sym_COLON,
  [719] = 2,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(180), 1,
      anon_sym_RBRACK,
  [726] = 2,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(182), 1,
      anon_sym_COLON,
  [733] = 2,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(184), 1,
      anon_sym_COMMA,
  [740] = 1,
    ACTIONS(154), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [745] = 2,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
  [752] = 2,
    ACTIONS(146), 1,
      sym_identifier,
    STATE(56), 1,
      sym_parameter,
  [759] = 2,
    ACTIONS(188), 1,
      anon_sym_DASH_GT,
    ACTIONS(190), 1,
      anon_sym_COLON,
  [766] = 1,
    ACTIONS(192), 1,
      anon_sym_RPAREN,
  [770] = 1,
    ACTIONS(194), 1,
      sym_identifier,
  [774] = 1,
    ACTIONS(196), 1,
      aux_sym_comment_token1,
  [778] = 1,
    ACTIONS(198), 1,
      sym_identifier,
  [782] = 1,
    ACTIONS(200), 1,
      anon_sym_LBRACK,
  [786] = 1,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
  [790] = 1,
    ACTIONS(204), 1,
      sym_identifier,
  [794] = 1,
    ACTIONS(206), 1,
      anon_sym_import,
  [798] = 1,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
  [802] = 1,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
  [806] = 1,
    ACTIONS(212), 1,
      sym_identifier,
  [810] = 1,
    ACTIONS(214), 1,
      ts_builtin_sym_end,
  [814] = 1,
    ACTIONS(216), 1,
      anon_sym_COLON,
  [818] = 1,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
  [822] = 1,
    ACTIONS(220), 1,
      anon_sym_EQ,
  [826] = 1,
    ACTIONS(222), 1,
      sym_identifier,
  [830] = 1,
    ACTIONS(224), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 103,
  [SMALL_STATE(6)] = 134,
  [SMALL_STATE(7)] = 159,
  [SMALL_STATE(8)] = 184,
  [SMALL_STATE(9)] = 209,
  [SMALL_STATE(10)] = 234,
  [SMALL_STATE(11)] = 251,
  [SMALL_STATE(12)] = 265,
  [SMALL_STATE(13)] = 279,
  [SMALL_STATE(14)] = 293,
  [SMALL_STATE(15)] = 307,
  [SMALL_STATE(16)] = 321,
  [SMALL_STATE(17)] = 335,
  [SMALL_STATE(18)] = 349,
  [SMALL_STATE(19)] = 363,
  [SMALL_STATE(20)] = 377,
  [SMALL_STATE(21)] = 391,
  [SMALL_STATE(22)] = 405,
  [SMALL_STATE(23)] = 419,
  [SMALL_STATE(24)] = 433,
  [SMALL_STATE(25)] = 447,
  [SMALL_STATE(26)] = 461,
  [SMALL_STATE(27)] = 470,
  [SMALL_STATE(28)] = 479,
  [SMALL_STATE(29)] = 488,
  [SMALL_STATE(30)] = 502,
  [SMALL_STATE(31)] = 516,
  [SMALL_STATE(32)] = 530,
  [SMALL_STATE(33)] = 544,
  [SMALL_STATE(34)] = 558,
  [SMALL_STATE(35)] = 572,
  [SMALL_STATE(36)] = 583,
  [SMALL_STATE(37)] = 592,
  [SMALL_STATE(38)] = 605,
  [SMALL_STATE(39)] = 611,
  [SMALL_STATE(40)] = 621,
  [SMALL_STATE(41)] = 627,
  [SMALL_STATE(42)] = 637,
  [SMALL_STATE(43)] = 647,
  [SMALL_STATE(44)] = 653,
  [SMALL_STATE(45)] = 663,
  [SMALL_STATE(46)] = 673,
  [SMALL_STATE(47)] = 679,
  [SMALL_STATE(48)] = 685,
  [SMALL_STATE(49)] = 695,
  [SMALL_STATE(50)] = 700,
  [SMALL_STATE(51)] = 705,
  [SMALL_STATE(52)] = 712,
  [SMALL_STATE(53)] = 719,
  [SMALL_STATE(54)] = 726,
  [SMALL_STATE(55)] = 733,
  [SMALL_STATE(56)] = 740,
  [SMALL_STATE(57)] = 745,
  [SMALL_STATE(58)] = 752,
  [SMALL_STATE(59)] = 759,
  [SMALL_STATE(60)] = 766,
  [SMALL_STATE(61)] = 770,
  [SMALL_STATE(62)] = 774,
  [SMALL_STATE(63)] = 778,
  [SMALL_STATE(64)] = 782,
  [SMALL_STATE(65)] = 786,
  [SMALL_STATE(66)] = 790,
  [SMALL_STATE(67)] = 794,
  [SMALL_STATE(68)] = 798,
  [SMALL_STATE(69)] = 802,
  [SMALL_STATE(70)] = 806,
  [SMALL_STATE(71)] = 810,
  [SMALL_STATE(72)] = 814,
  [SMALL_STATE(73)] = 818,
  [SMALL_STATE(74)] = 822,
  [SMALL_STATE(75)] = 826,
  [SMALL_STATE(76)] = 830,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 8, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_docstring, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_docstring, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 7, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant_definition, 7, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant_definition, 7, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 4, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 4, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_type, 6, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 5, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [214] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vyper(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "vyper",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
